spring:
  application:
    name: CardService
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: card_service
    password: Dt3C4rD5
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
security:
  encryption:
    key: 3393367639794567 # in a production setting,
    # I would use a Key management service like AWS KMS,
    #Azure Key Vault or the postgres extension for encryption
    iv: 3393367639794567
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true