version: '3.8'

services:
  discovery-service:
    image: discovery-service:latest
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image: gateway:latest
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service


  account-service:
    image: account-service:latest
    build:
      context: ./AccountService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service


  card-service:
    image: card-service:latest
    build:
      context: ./CardService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service

  customer-service:
    image: customer-service:latest
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service


