spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: customer_service
    password: Dt3Cu5tomer
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
