spring:
  application:
    name: AccountService
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: account_service
    password: Dt3AcC0un7
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
